//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbanianXrm.EarlyBound.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AlbanianXrm.EarlyBound.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection has changed to: {0}.
        /// </summary>
        public static string CONNECTION_CHANGED {
            get {
                return ResourceManager.GetString("CONNECTION_CHANGED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To contribute to this plugin visit its code repository.
        /// </summary>
        public static string CONTRIBUTE_NOTIFICATION {
            get {
                return ResourceManager.GetString("CONTRIBUTE_NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Albanian-Xrm/Early-Bound.
        /// </summary>
        public static string CONTRIBUTE_URI {
            get {
                return ResourceManager.GetString("CONTRIBUTE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} package not found on {1}.
        /// </summary>
        public static string CORE_TOOLS_NOT_FOUND {
            get {
                return ResourceManager.GetString("CORE_TOOLS_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmSvcUtil.exe is missing. Please download CoreTools..
        /// </summary>
        public static string CRMSVCUTIL_MISSING {
            get {
                return ResourceManager.GetString("CRMSVCUTIL_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting latest version of Core Tools.
        /// </summary>
        public static string DOWNLOADING_CORE_TOOLS {
            get {
                return ResourceManager.GetString("DOWNLOADING_CORE_TOOLS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C# (*.cs)|*.cs.
        /// </summary>
        public static string FILTER_C_SHARP {
            get {
                return ResourceManager.GetString("FILTER_C_SHARP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visual Basic (*.vb)|*.vb.
        /// </summary>
        public static string FILTER_VISUAL_BASIC {
            get {
                return ResourceManager.GetString("FILTER_VISUAL_BASIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generating Early-Bound Classes.
        /// </summary>
        public static string GENERATING_ENTITIES {
            get {
                return ResourceManager.GetString("GENERATING_ENTITIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting attributes for entity {0}.
        /// </summary>
        public static string GETTING_ATTRIBUTES {
            get {
                return ResourceManager.GetString("GETTING_ATTRIBUTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting entity list.
        /// </summary>
        public static string GETTING_ENTITY_LIST {
            get {
                return ResourceManager.GetString("GETTING_ENTITY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting relationships for entity {0}.
        /// </summary>
        public static string GETTING_RELATIONSHIPS {
            get {
                return ResourceManager.GetString("GETTING_RELATIONSHIPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft.IO.RecyclableMemoryStream.dll is missing. Please reinstall Albanian Early Bound..
        /// </summary>
        public static string MEMORYSTREAM_MISSING {
            get {
                return ResourceManager.GetString("MEMORYSTREAM_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving current settings.
        /// </summary>
        public static string SAVING_SETTINGS {
            get {
                return ResourceManager.GetString("SAVING_SETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command selects all entities..
        /// </summary>
        public static string SELECT_ALL_NO_REQUEST {
            get {
                return ResourceManager.GetString("SELECT_ALL_NO_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This command will retrieve all entity metadata and select all of them..
        /// </summary>
        public static string SELECT_ALL_REQUEST {
            get {
                return ResourceManager.GetString("SELECT_ALL_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting the last generated entity attributes and relationships..
        /// </summary>
        public static string SELECTING_GENERATED {
            get {
                return ResourceManager.GetString("SELECTING_GENERATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings found and loaded.
        /// </summary>
        public static string SETTINGS_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings not found =&gt; a new settings file has been created!.
        /// </summary>
        public static string SETTINGS_NOT_FOUND {
            get {
                return ResourceManager.GetString("SETTINGS_NOT_FOUND", resourceCulture);
            }
        }
    }
}
